name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  rust-check:
    name: Run Various Cargo Checks
    runs-on: ubuntu-latest

    steps:
    - name: Run Checks
      uses: will-lynas/rust-check-ci@v0.1.0
